### ISSUE TITLE
Authentication not working for subdomains of the app.

### ISSUE THREAD

**Issue by salomartin** [Shopify/ui-extensions#1690]
## Please list the package(s) involved in the issue, and include the version you are using
@shopify/ui-extensions-react 2024.1.1

## Describe the bug

The docs https://shopify.dev/docs/api/admin-extensions#app-authentication say that "When you use fetch() to make a request to your app's configured auth domain or any of its subdomains, an Authorization header is automatically added". Yet this doesn't happen for the subdomains, and the source for the wrappedFetch indicates as much:
```
let f = t && s.origin === t;
if (s.protocol !== "https:")
    throw new Y("URL must be secure (HTTPS)");
if (!e?.auth || !f)
    return q(r, c);
let m = await e.auth.getSessionToken();
c.headers.set("Authorization", `Bearer ${m}`);
```
It seems to simply check the origin against the app url. No checks for subdomains. It also doesn't seem to be possible to call the getSessionToken from anywhere in the admin extensions as the new @shopify/ui-extensions-react/admin simply doesn't contain it. Am I missing something, or is the documentation faulty? And if so, then how to resolve this?

## Steps to reproduce the behavior:

1. Create an app from latest remix template
2. Create an admin action extension
3. Fetch something from subdomain of the app

## Expected behavior

Get request should have Authorization headers with session token

**Comment by MitchLillie** [comment]
Hi @salomartin! This should now be fixed. Can you take a look on your end and confirm that the issue is resolved?

**Comment by mattsodomsky** [comment]
I'm still having the issue @salomartin - were you able to get this working?
